# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  btrfsOpts = [ "noatime" "ssd" "space_cache=v2" "discard=async" "compress=zstd:3" ];
  btrfsDev  = "/dev/disk/by-uuid/94bcd5e3-ec96-4a28-80b2-f987d18c8a12";
in
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = btrfsDev;
    fsType = "btrfs";
    options = [ "subvol=@" ] ++ btrfsOpts;
  };

  fileSystems."/home" = {
    device = btrfsDev;
    fsType = "btrfs";
    options = [ "subvol=@home" ] ++ btrfsOpts;
  };

  fileSystems."/nix" = {
    device = btrfsDev;
    fsType = "btrfs";
    options = [ "subvol=@nix" ] ++ btrfsOpts;
  };

  fileSystems."/persist" = {
    device = btrfsDev;
    fsType = "btrfs";
    options = [ "subvol=@persist" ] ++ btrfsOpts;
  };

  fileSystems."/.snapshots" = {
    device = btrfsDev;
    fsType = "btrfs";
    options = [ "subvol=@snapshots" ] ++ btrfsOpts;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9715-401E";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c4072834-5654-415d-a8af-95e8e160dc5b"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

