[package]
name = "cursor-history-lock"
version = "0.1.0"
edition = "2021"
rust-version = "1.89"

[lib]
name = "cursor_history_lock"
crate-type = ["cdylib"]

[dependencies]
steel-core = {
    git = "https://github.com/mattwparas/steel.git",
    rev = "118fb9f9257dd518db92c093e230c3392b8fd520",
    features = ["anyhow", "dylibs", "sync", "biased", "imbl"]
}
abi_stable = "0.11.3"
